## OpenCV 

OpenCV is the huge open-source library for the computer vision, machine learning, and image processing. It was originally developed by Intel in 1999. OpenCV is written in C++ and its primary interface is in C++. All of the new developments and algorithms appear in the C++ interface. There are bindings in Python, Java and MATLAB/OCTAVE.

### Content:

* Read Image
    * Find size of image
    * Display height, width and number of channels
* Display Image 
    * Read grayscale and display
    * Display different channels
* Split and Merge different channels
* Write Image
* Convert Colour Space
    * Convert from BGR to HSV 
    * Convert from BGR to RGB
    * Convert from RGB to Gray

In [25]:
#Installing OpenCV in python
#!pip install opencv-python

In [26]:
# Import OpenCV library
import cv2
import os

# Read image 

The images are read as numpy array which are three dimensional. The first dimension is width, second is height, and the third is the number of channels. In case of colour images it is three. 

In [27]:
image_path=os.path.join('images','Dreaming_about_a_horse.jpg')
image_1=cv2.imread(image_path)
print('The shape of the image is: ', image_1.shape)
print('Height: ',image_1.shape[0])
print('Width: ',image_1.shape[1])
print('Channels: ',image_1.shape[2])

The shape of the image is:  (450, 600, 3)
Height:  450
Width:  600
Channels:  3


### Expected Output:
The shape of the image is:  (450, 600, 3)<br>
Height:  450<br>
Width:  600<br>
Channels:  3<br>

In [28]:
print('Data Type of opencv read image', type(image_1))

Data Type of opencv read image <class 'numpy.ndarray'>


### Expected Output:

Data Type of opencv read image <class 'numpy.ndarray'>


In [29]:
image_path=os.path.join('images','lion.jpeg')
image_2=cv2.imread(image_path)
print('The shape of the image is: ', image_2.shape)

The shape of the image is:  (183, 275, 3)


### Expected Output:
The shape of the image is:  (183, 275, 3)


# Display image using opencv

In [30]:
#cv2.imshow('Window_name',image_array)
cv2.imshow('Horse',image_1)
cv2.imshow('Lion',image_2)
cv2.waitKey()
cv2.destroyAllWindows()

### Expected output:
####  Displaying saved screenshot of the output
![title](output/Screenshot_windows.png)

### Read colour image as grayscale Image

In [31]:
img=cv2.imread(os.path.join('images','Dreaming_about_a_horse.jpg'),0 )
cv2.imshow('Grayscale_image',img)
cv2.waitKey()
cv2.destroyAllWindows()

### Expected Output:

![title](output/Screenshot_read_grayscale.png)

In [11]:
print('The size of grayscale image is ',img.shape)
print(f'It is a  {len(img.shape)} dimensional array')

The size of grayscale image is  (450, 600)
It is a  2 dimensional array


### Expected output:
The size of grayscale image is  (450, 600)<br>
It is a  2 dimensional array<br>

### Printing channel values at random pixels

In [12]:
#For the horse image
import numpy as np # for generating random number
np.random.seed(0)
for i in range(3):
    x=np.random.randint(image_1.shape[0])
    y=np.random.randint(image_1.shape[1])
    print(f'x={x} and y={y}, pixel values are: {image_1[x,y,:]}')

x=172 and y=559, pixel values are: [ 60  62 102]
x=117 and y=192, pixel values are: [ 36  66 125]
x=323 and y=359, pixel values are: [138 133 124]


### Expected Output:

x=172 and y=559, pixel values are: [ 60  62 102]<br>
x=117 and y=192, pixel values are: [ 36  66 125]<br>
x=323 and y=359, pixel values are: [138 133 124]<br>

In [13]:
#Although, the image of the Lion looks a grayscale image. 
#But it still has three channels where all the channels has same values as shown below.
import numpy as np # for generating random number
np.random.seed(0)
for i in range(3):
    x=np.random.randint(image_2.shape[0])
    y=np.random.randint(image_2.shape[1])
    print(f'x={x} and y={y}, pixel values are: {image_2[x,y,:]}')

x=172 and y=47, pixel values are: [70 70 70]
x=117 and y=192, pixel values are: [28 28 28]
x=67 and y=251, pixel values are: [214 214 214]


### Expected Output: 
* The pixel values at all the three channels are same

x=172 and y=47, pixel values are: [70 70 70]<br>
x=117 and y=192, pixel values are: [28 28 28]<br>
x=67 and y=251, pixel values are: [214 214 214]<br>

# Display the different channels of the image in different windows

The three channels in different windows looks like grayscale image where the value at intensity at each pixel is the value of the channel.  

In [14]:
channel_1=image_1[:,:,0]
channel_2=image_1[:,:,1]
channel_3=image_1[:,:,2]
cv2.imshow('Channel 1',channel_1)
cv2.imshow('Channel 2',channel_2)
cv2.imshow('Channel 3',channel_3)

cv2.waitKey()
cv2.destroyAllWindows()

## The expected output:
![title](output/Screenshot_channels.png)

# OpenCV reads the image channel as BGR not RGB

In the image below, we can see the value of different channels R,G,B at pixel [126,313]. Also we print the value of different channels of image read using cv2 where the first channel value match with B, second channel with G and third channel with R.

![title](output/Horse_pixel_screenshot.png)

In [15]:
print('Channel 1 = ',channel_1[126,313])
print('Channel 2 = ',channel_2[126,313])
print('Channel 3 = ',channel_3[126,313])

Channel 1 =  126
Channel 2 =  170
Channel 3 =  217


-----------------------------------
### Expected Output:

Channel 1 =  126<br>
Channel 2 =  170<br>
Channel 3 =  217<br>

# Displaying each channel as coloured image channel B as Blue, channel G as Green and channel R as Red

In [16]:
channel_B=np.zeros(image_1.shape,dtype='uint8') #image with zeros in the three channels
channel_B[:,:,0]=channel_1
cv2.imshow('Blue',channel_B)

channel_G=np.zeros(image_1.shape,dtype='uint8') #image with zeros in the three channels
channel_G[:,:,1]=channel_2
cv2.imshow('Green',channel_G)

channel_R=np.zeros(image_1.shape,dtype='uint8') #image with zeros in the three channels
channel_R[:,:,2]=channel_3
cv2.imshow('Red',channel_R)

cv2.waitKey()
cv2.destroyAllWindows()

## The output will be as follows
![title](output/Screenshot_BGR.png)

# Split and Merge Channels OpenCV

In [17]:
#another way to split the channels of image is 
B,G,R=cv2.split(image_1)

In [18]:
merged_image=cv2.merge([B,G*2,R])
cv2.imshow('Merged Image with more Green', merged_image)
cv2.waitKey()
cv2.destroyAllWindows()

## The expected output
![title](output/Screenshot_merged_image.png)

## Write Image

In [19]:
cv2.imwrite(os.path.join('images','Image_name.jpg'),image_1)

True

In [20]:
img=cv2.imread(os.path.join('images','Image_name.jpg'))

In [21]:
cv2.imshow('Window',img)
cv2.waitKey()
cv2.destroyAllWindows()

# Convert Colour Space

In [22]:
image_path=os.path.join('images','Dreaming_about_a_horse.jpg')
image=cv2.imread(image_path)
HSV_image=cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
cv2.imshow('HSV image',HSV_image)
cv2.waitKey()
cv2.destroyAllWindows()

## The expected output
![title](output/HSV_img.png)

In [23]:
# BGR to RGB conversion
RGB_image=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
cv2.imshow('RGB image',RGB_image)
cv2.waitKey()
cv2.destroyAllWindows()


#### The cv2.imshow considers the image to be in BGR format, i.e., first channel as Blue. 
#### Therefore the displayed RGB image will be in different as compared to original image. 

### Expected Output:
![title](output/BGR2RGB_image.png)


In [24]:
# RGB to gray conversion
Gray_image=cv2.cvtColor(RGB_image,cv2.COLOR_RGB2GRAY)
cv2.imshow('RGB2Grayimage',Gray_image)
Gray_image=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('BGR2Gray image',Gray_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Expected Output:
 
 ![title](output/imgage1.png)


# <center> Thank You